# Generated by Django 3.2.18 on 2023-04-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20230429_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
    ]
