# Generated by Django 3.2.18 on 2023-04-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_listing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
