# Generated by Django 3.2.18 on 2023-04-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
    ]
