# Generated by Django 3.2.18 on 2023-04-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
